const API_BASE = window.ABS_API_BASE || `${location.origin}/api`;
const $=id=>document.getElementById(id);
let adminToken=sessionStorage.getItem('abs_admin_token')||'';
let state={users:[],feedback:[],ads:[],summary:{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const escAttr=v=>esc(v).replace(/`/g,'&#96;');

function api(path,opts={}){const headers=Object.assign({'Content-Type':'application/json'},opts.headers||{});if(adminToken)headers.Authorization=`Bearer ${adminToken}`;return fetch(`${API_BASE}${path}`,{...opts,headers}).then(async r=>{let d={};try{d=await r.json()}catch{}if(!r.ok){if(r.status===401){adminToken='';sessionStorage.removeItem('abs_admin_token');showLogin();}throw new Error(d.error||`Request failed (${r.status})`)}return d})}
function login(){const username=$('adminUser').value.trim(),password=$('adminPass').value;api('/admin/login',{method:'POST',body:JSON.stringify({username,password})}).then(d=>{adminToken=d.token;sessionStorage.setItem('abs_admin_token',adminToken);showAdmin()}).catch(e=>$('loginMsg').textContent=e.message)}
function showLogin(){$('login').classList.remove('hidden');$('app').classList.add('hidden')}
function showAdmin(){$('login').classList.add('hidden');$('app').classList.remove('hidden');refreshAdmin()}
function adminLogout(){adminToken='';sessionStorage.removeItem('abs_admin_token');showLogin()}
async function refreshAdmin(){try{const [sum,users,feedback,ads]=await Promise.all([api('/admin/summary'),api('/admin/users'),api('/admin/feedback'),api('/ads').catch(()=>({items:[]}))]);state.summary=sum;state.users=users.items||[];state.feedback=feedback.items||[];state.ads=ads.items||[];renderStats();renderUsers();renderAds();renderFeedback()}catch(e){if($('loginMsg'))$('loginMsg').textContent=e.message}}
function renderStats(){const s=state.summary;$('userCount').textContent=s.users??state.users.length;$('feedbackCount').textContent=s.feedback??state.feedback.length;$('adCount').textContent=s.ads??state.ads.filter(a=>a.active).length;$('verifiedCount').textContent=s.verified??state.users.filter(u=>u.verified).length;if($('requestCount'))$('requestCount').textContent=s.premium??state.users.filter(u=>u.premium).length}
function renderUsers(){const list=state.users;$('users').innerHTML=list.length?list.map(u=>`<div class="user"><div class="userhead"><div><div class="name">${esc(u.name)}${u.verified?'<span class="verify">✓</span>':''}</div><div class="mobile">${esc(u.mobile)}</div><div class="sub"><b>ABS ID:</b> ${esc(u.abs_id||'—')} · ${u.premium?'PREMIUM':'STANDARD'}</div></div><span class="badge">${u.verified?'VERIFIED':'REGISTERED'}</span></div><div class="sub">Created: ${esc(formatDate(u.created_at))}</div><div class="row"><button class="btn" onclick="openUserManager(${u.id})">VIEW / MANAGE</button><button class="btn ${u.verified?'secondary':'blue'}" onclick="toggleVerified(${u.id},${!u.verified})">${u.verified?'REMOVE BLUE TICK':'✓ VERIFY ACCOUNT'}</button><button class="btn danger" onclick="deleteUser(${u.id})">DELETE ACCOUNT</button></div></div>`).join(''):'<div class="empty">No registered users found.</div>'}
function openUserManager(id){const u=state.users.find(x=>x.id===id);if(!u)return;$('modalTitle').textContent='User Account';$('modalBody').innerHTML=`<p class="muted"><b>${esc(u.name)}</b><br>${esc(u.mobile)}</p><label>ABS ID</label><input id="editAbsId" value="${escAttr(u.abs_id||'')}" placeholder="ABS701001"><label>Display Name</label><input id="editName" value="${escAttr(u.name||'')}"><div id="userMsg" class="msg"></div><button class="btn full" onclick="saveUser(${u.id})">SAVE USER</button><div class="row"><button class="btn ${u.verified?'secondary':'blue'}" onclick="toggleVerified(${u.id},${!u.verified})">${u.verified?'REMOVE BLUE TICK':'✓ VERIFY ACCOUNT'}</button><button class="btn ok" onclick="togglePremium(${u.id},${!u.premium})">${u.premium?'REMOVE PREMIUM':'MAKE PREMIUM'}</button></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><div class="sub">Password is never displayed. Admin can set a new password.</div><button class="btn full" style="margin-top:10px" onclick="changePassword(${u.id})">RESET PASSWORD</button><button class="btn danger full" style="margin-top:10px" onclick="deleteUser(${u.id})">DELETE ACCOUNT</button>`;$('modal').classList.remove('hidden')}
function saveUser(id){const name=$('editName').value.trim(),abs_id=$('editAbsId').value.trim();if(!name||!abs_id)return $('userMsg').textContent='Name and ABS ID are required.';api(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({name,abs_id})}).then(()=>{closeModal();refreshAdmin()}).catch(e=>$('userMsg').textContent=e.message)}
function toggleVerified(id,value){api(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({verified:value})}).then(refreshAdmin).catch(e=>alert(e.message))}
function togglePremium(id,value){api(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify({premium:value})}).then(()=>{closeModal();refreshAdmin()}).catch(e=>alert(e.message))}
function changePassword(id){$('modalTitle').textContent='Reset User Password';$('modalBody').innerHTML=`<label>New Password</label><input id="newPass" type="password" minlength="6"><label>Confirm Password</label><input id="newPass2" type="password" minlength="6"><div id="passMsg" class="msg"></div><button class="btn full" onclick="savePassword(${id})">UPDATE PASSWORD</button>`}
function savePassword(id){const a=$('newPass').value,b=$('newPass2').value;if(a.length<6)return $('passMsg').textContent='Password must be at least 6 characters.';if(a!==b)return $('passMsg').textContent='Passwords do not match.';api(`/admin/users/${id}/reset-password`,{method:'POST',body:JSON.stringify({password:a})}).then(()=>{closeModal();alert('Password updated successfully.')}).catch(e=>$('passMsg').textContent=e.message)}
function deleteUser(id){const u=state.users.find(x=>x.id===id);if(!u||!confirm(`Delete the account of ${u.name}? This permanently removes the account and its server-side data.`))return;api(`/admin/users/${id}`,{method:'DELETE'}).then(()=>{closeModal();refreshAdmin()}).catch(e=>alert(e.message))}
function openCreateUser(){$('modalTitle').textContent='Create User Account';$('modalBody').innerHTML=`<p class="muted">Create an account directly in the central database.</p><label>Full Name</label><input id="createName"><label>Mobile Number</label><input id="createMobile" inputmode="numeric" maxlength="10"><label>Password</label><input id="createPass" type="password" minlength="6"><label>Confirm Password</label><input id="createPass2" type="password" minlength="6"><div id="createMsg" class="msg"></div><button class="btn full" onclick="createUser()">CREATE ACCOUNT</button>`;$('modal').classList.remove('hidden')}
function createUser(){const name=$('createName').value.trim(),mobile=$('createMobile').value.trim(),p=$('createPass').value,p2=$('createPass2').value;if(!name)return $('createMsg').textContent='Enter the user name.';if(!/^[6-9]\d{9}$/.test(mobile))return $('createMsg').textContent='Enter a valid 10-digit Indian mobile number.';if(p.length<6)return $('createMsg').textContent='Password must be at least 6 characters.';if(p!==p2)return $('createMsg').textContent='Passwords do not match.';api('/admin/users',{method:'POST',body:JSON.stringify({name,mobile,password:p})}).then(()=>{closeModal();refreshAdmin();alert('Account created successfully.')}).catch(e=>$('createMsg').textContent=e.message)}
function renderAds(){$('ads').innerHTML=state.ads.length?state.ads.map(a=>`<div class="ad"><div class="adtitle">${esc(a.title||'Advertisement')}</div><div class="sub">${esc(a.text||'')}</div>${a.image?`<img src="${esc(a.image)}" alt="">`:''}<div class="ad-actions"><button class="btn ${a.active?'ok':'blue'}" onclick="toggleAd(${a.id},${!a.active})">${a.active?'ACTIVE':'ENABLE'}</button><button class="btn danger" onclick="deleteAd(${a.id})">DELETE</button></div></div>`).join(''):'<div class="empty">No advertisements added yet.</div>'}
function openAdModal(id=null){const a=id?state.ads.find(x=>x.id===id):{badge:'FEATURED',title:'',text:'',link:'',image:'',active:true};$('modalTitle').textContent=id?'Edit Advertisement':'Add Advertisement';$('modalBody').innerHTML=`<label>Upload Image</label><input id="adImageFile" type="file" accept="image/*"><div class="preview" id="adPreview">${a.image?`<img src="${esc(a.image)}">`:''}</div><label>Badge</label><input id="adBadge" value="${escAttr(a.badge||'FEATURED')}"><label>Title</label><input id="adTitle" value="${escAttr(a.title||'')}"><label>Text</label><textarea id="adText">${esc(a.text||'')}</textarea><label>Link (optional)</label><input id="adLink" value="${escAttr(a.link||'')}"><button class="btn full" style="margin-top:16px" onclick="saveAd(${id||0})">SAVE ADVERTISEMENT</button><div id="adMsg" class="msg"></div>`;window._adImage=a.image||'';$('adImageFile').onchange=()=>{const f=$('adImageFile').files?.[0];if(!f)return;if(f.size>2*1024*1024)return $('adMsg').textContent='Use an image smaller than 2 MB.';const r=new FileReader();r.onload=e=>{window._adImage=e.target.result;$('adPreview').style.display='block';$('adPreview').innerHTML=`<img src="${e.target.result}" alt="">`};r.readAsDataURL(f)};$('modal').classList.remove('hidden')}
function saveAd(id){const title=$('adTitle').value.trim();if(!title)return $('adMsg').textContent='Title is required.';const body={badge:$('adBadge').value.trim()||'FEATURED',title,text:$('adText').value.trim(),link:$('adLink').value.trim(),image:window._adImage||'',active:true};const req=id?api(`/admin/ads/${id}`,{method:'PATCH',body:JSON.stringify(body)}):api('/admin/ads',{method:'POST',body:JSON.stringify(body)});req.then(()=>{closeModal();refreshAdmin()}).catch(e=>$('adMsg').textContent=e.message)}
function toggleAd(id,active){api(`/admin/ads/${id}`,{method:'PATCH',body:JSON.stringify({active})}).then(refreshAdmin).catch(e=>alert(e.message))}
function deleteAd(id){if(!confirm('Delete this advertisement?'))return;api(`/admin/ads/${id}`,{method:'DELETE'}).then(refreshAdmin).catch(e=>alert(e.message))}
function renderFeedback(){$('feedback').innerHTML=state.feedback.length?state.feedback.map(f=>`<div class="feedback"><b>${esc(f.type||'Feedback')}</b><div class="sub">${esc(f.message||'')}</div><div class="sub">${esc(f.name||'User')} · ${esc(f.mobile||'')} · ${esc(formatDate(f.created_at))}</div></div>`).join(''):'<div class="empty">No feedback yet.</div>'}
function formatDate(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
function closeModal(){$('modal').classList.add('hidden');window._adImage=''}
if(adminToken)showAdmin();else showLogin();
window.refreshAdmin=refreshAdmin;window.adminLogout=adminLogout;window.openCreateUser=openCreateUser;window.openUserManager=openUserManager;window.toggleVerified=toggleVerified;window.togglePremium=togglePremium;window.changePassword=changePassword;window.deleteUser=deleteUser;window.saveUser=saveUser;window.savePassword=savePassword;window.createUser=createUser;window.openAdModal=openAdModal;window.saveAd=saveAd;window.toggleAd=toggleAd;window.deleteAd=deleteAd;window.closeModal=closeModal;
